# Generated by Django 5.0.4 on 2024-04-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_file',
            field=models.FileField(blank=True, null=True, upload_to='job/'),
        ),
    ]
