# Generated by Django 5.0.4 on 2024-04-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_job_job_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
