# Generated by Django 5.0.4 on 2024-04-24 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_is_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='resume',
            name='qualification',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
