# Generated by Django 5.0.4 on 2024-04-25 06:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_resume_skills_alter_resume_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
