# Generated by Django 5.0.4 on 2024-04-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_salary_job_max_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('seeker', 'Seeker'), ('recruiter', 'Recruiter'), ('admin', 'Admin')], max_length=20),
        ),
    ]
