# Generated by Django 5.0.4 on 2024-04-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_avater_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(default=1, upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
