# Generated by Django 5.0.4 on 2024-05-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'job')},
        ),
    ]
