# Generated by Django 5.0.4 on 2024-05-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.CharField(default='Need a good lawyer', max_length=300),
            preserve_default=False,
        ),
    ]
