# Generated by Django 5.0.4 on 2024-05-05 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='api.application'),
        ),
    ]
